package com.avbravo.jettraserverhelloworld.repository;
// <editor-fold defaultstate="collapsed" desc="imports">

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.annotation.PostConstruct;
/**
* MongoDB
*/
import com.jmoordb.core.processor.model.JmoordbException;
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.eq;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import org.bson.Document;
import com.mongodb.client.result.InsertOneResult;
import org.bson.conversions.Bson;
import com.mongodb.client.model.Filters;
import com.mongodb.client.result.UpdateResult;
import com.mongodb.client.model.UpdateOptions;
import com.mongodb.client.ListIndexesIterable;
import com.mongodb.client.MongoIterable;
/**
* Java
*/
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import com.jmoordb.core.util.MessagesUtil;
import com.jmoordb.core.model.Pagination;
import com.jmoordb.core.model.Sorted;
import com.avbravo.jettraserverhelloworld.model.Country;
import com.jettraserver.config.JettraConfig;



// </editor-fold>
@ApplicationScoped
public class CountryRepositoryImpl  implements CountryRepository, JettraConfig {
// <editor-fold defaultstate="collapsed" desc="inject">

    @Inject
    MongoClient mongoClient;
/**
* Microprofile Config
*/
//    @Inject
//    Config config;
//    @Inject
//    @ConfigProperty(name = "mongodb.database")
//    String mongodbDatabase;
String mongodbDatabase =getMicroprofileConfig("mongodb.database");
    String mongodbCollection = "country";
/**
* AutogeneratedRepository
*/
    @Inject
    com.avbravo.jettraserverhelloworld.repository.AutogeneratedRepository autogeneratedRepository;
/**
* Supplier
*/
    @Inject
    com.avbravo.jettraserverhelloworld.model.CountrySupplier countrySupplier;
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="Exception">

   private JmoordbException exception;
public JmoordbException getJmoordbException() {
   if(exception == null || exception.getLocalizedMessage()== null ){
    exception = new JmoordbException("");
   }
    return exception;
 }
public void setJmoordbException(JmoordbException exception) {    this.exception = exception; }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="java.util.List<com.avbravo.jettraserverhelloworld.model.Country> lookup(com.jmoordb.core.model.Search search ) ">

    @Override
    public java.util.List<com.avbravo.jettraserverhelloworld.model.Country> lookup(com.jmoordb.core.model.Search search) {
        List<Country> list = new ArrayList<>();
        try {
           MongoCollection<Document> collection = getCollection().get();
               MongoCursor<Document> cursor;
               Document sortQuery = new Document();
               if (search.getSorted().getSort() == null || search.getSorted().getSort().isEmpty()) {
               } else {
                   sortQuery = search.getSorted().getSort();
               }
               if (search.getPagination() == null || search.getPagination().getPage() < 1) {
                  cursor = collection.find(search.getFilter()).allowDiskUse(Boolean.TRUE).sort(sortQuery).iterator();
               } else {
                    cursor = collection.find(search.getFilter()).allowDiskUse(Boolean.TRUE)
                                        .skip(search.getPagination().skip())
                                        .limit(search.getPagination().limit())
                                        .sort(sortQuery).iterator();
               }
               try{
                  while (cursor.hasNext()) {
                       list.add(countrySupplier.get(Country::new, cursor.next()));
                  }
               } finally {
                     cursor.close();
               } 
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
              exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return list;

     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="java.lang.Long count(com.jmoordb.core.model.Search[] search ) ">

    @Override
    public java.lang.Long count(com.jmoordb.core.model.Search[] search) {
        Long contador = 0L;
        try {
           MongoCollection<Document> collection = getCollection().get();
               Document whereCondition = new Document();
               if (search.length != 0) {
                  whereCondition = search[0].getFilter();
               } 
               if (whereCondition.isEmpty()) {
                  contador = collection.countDocuments();
               } else {
                  contador = collection.countDocuments(whereCondition);
               }
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
              exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return contador;
     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="java.lang.Long countLikeByCountry(java.lang.String country ) ">

    @Override
    public java.lang.Long countLikeByCountry(java.lang.String country) {
        Long contador = 0L;
        try {
           MongoCollection<Document> collection = getCollection().get();
               		contador = collection.countDocuments(  new Document("country", new Document("$regex", country).append("$options", "i")));


         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
               exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return contador;
     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="java.util.List<com.avbravo.jettraserverhelloworld.model.Country> likeByCountry(java.lang.String country ) ">

    @Override
    public java.util.List<com.avbravo.jettraserverhelloworld.model.Country> likeByCountry(java.lang.String country) {
        List<Country> list = new ArrayList<>();
        try {
           MongoCollection<Document> collection = getCollection().get();
               MongoCursor<Document> cursor;
             Document sort = new Document("country",1);
               		Document filter = new Document("country", new Document("$regex", country).append("$options", "i"));

		cursor = collection.find( filter ).allowDiskUse(Boolean.TRUE)
				.sort(sort)
	.iterator();

               try{
                  while (cursor.hasNext()) {
                        list.add(countrySupplier.get(Country::new, cursor.next()));
                  }
               } finally {
                     cursor.close();
               } 
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
               exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return list;

     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc=" public Optional<Country> save(Country country)">

    @Override
    public Optional<Country> save(Country country) {
        try {
               String mongodbDatabaseValue = mongodbDatabase;
               String mongodbCollectionValue = mongodbCollection;
               if (!getDynamicDatabase().equals("")) {
                   mongodbDatabaseValue = getDynamicDatabase();
                }
               if (!getDynamicCollection().equals("")) {
                   mongodbCollectionValue = getDynamicCollection();
                }
               MongoDatabase database = mongoClient.getDatabase(mongodbDatabaseValue);
               setDynamicDatabase("");
               MongoCollection<Document> collection = database.getCollection(mongodbCollectionValue);
               setDynamicCollection("");
                              
               if (findByPkInternal(country.getIdcountry(),mongodbDatabaseValue,  mongodbCollectionValue).isPresent()) { 
                   MessagesUtil.warning("There is already a record with that id");
                    exception = new JmoordbException("There is already a record with that id");
                  return Optional.of(country);
               }
               
              Boolean haveId = Boolean.FALSE;
               Document doc =countrySupplier.toDocument(country);
             if(doc.containsKey("_id")){
                   haveId = Boolean.TRUE;
                   doc.remove("_id");
             }
            InsertOneResult insertOneResult = collection.insertOne(doc);

               if (insertOneResult.getInsertedId() != null) {
                  	if (haveId) {
	String _id =insertOneResult.getInsertedId().asObjectId().toString();
         _id = _id.substring(_id.indexOf("{")+1,_id.indexOf("}"));
         _id = _id.replace("value=", "");
         country = countrySupplier.putObjectId(country,_id);
	}
return Optional.of(country);
               }
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
               exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return Optional.empty();
     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="Boolean update(Country country)">

    @Override
    public Boolean update(Country country) {
        try {
               String mongodbDatabaseValue = mongodbDatabase;
               String mongodbCollectionValue = mongodbCollection;
               if (!getDynamicDatabase().equals("")) {
                   mongodbDatabaseValue = getDynamicDatabase();
                }
               if (!getDynamicCollection().equals("")) {
                   mongodbCollectionValue = getDynamicCollection();
                }
               MongoDatabase database = mongoClient.getDatabase(mongodbDatabaseValue);
               setDynamicDatabase("");
               MongoCollection<Document> collection = database.getCollection(mongodbCollectionValue);
               setDynamicCollection("");
               if (!findByPkInternal(country.getIdcountry(),mongodbDatabaseValue,  mongodbCollectionValue).isPresent()) { 
                   MessagesUtil.warning("Not found a record with that id");
                    exception = new JmoordbException("Not found a record with that id");
                    return Boolean.FALSE;
               }
               Bson filter = Filters.empty();
               filter = Filters.eq("idcountry",country.getIdcountry());
               UpdateOptions options = new UpdateOptions().upsert(false);
               UpdateResult result = collection.updateOne(filter,countrySupplier.toUpdate(country),options);
               if (result.getModifiedCount() > 0) {
                  return Boolean.TRUE;
               }
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
               exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return Boolean.FALSE;
     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="public List<Country> findAllPaginationSorted(Pagination pagination, Sorted sorted)">

    @Override
    public List<Country> findAllPaginationSorted(Pagination pagination, Sorted sorted) {
        List<Country> list = new ArrayList<>();
        try {
           MongoCollection<Document> collection = getCollection().get();
               MongoCursor<Document> cursor;
               		cursor = collection.find().allowDiskUse(Boolean.TRUE)
					.skip(pagination.skip())
			.limit(pagination.limit())
			.sort(sorted.getSort())
		.iterator();

               try{
                  while (cursor.hasNext()) {
                        list.add(countrySupplier.get(Country::new, cursor.next()));
                  }
               } finally {
                     cursor.close();
               } 
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
               exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return list;

     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="public List<Country> findAll()">

    @Override
    public List<Country> findAll() {
        List<Country> list = new ArrayList<>();
        try {
            System.out.println(".... llego al findAll()....");
           MongoCollection<Document> collection = getCollection().get();
               MongoCursor<Document> cursor;
               		cursor = collection.find().allowDiskUse(Boolean.TRUE)
				.iterator();

               try{
                  while (cursor.hasNext()) {
                        list.add(countrySupplier.get(Country::new, cursor.next()));
                  }
               } finally {
                     cursor.close();
               } 
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
               exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return list;

     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="public List<Country> findAllPagination(Pagination pagination)">

    @Override
    public List<Country> findAllPagination(Pagination pagination) {
        List<Country> list = new ArrayList<>();
        try {
           MongoCollection<Document> collection = getCollection().get();
               MongoCursor<Document> cursor;
               		cursor = collection.find().allowDiskUse(Boolean.TRUE)
					.skip(pagination.skip())
			.limit(pagination.limit())
		.iterator();

               try{
                  while (cursor.hasNext()) {
                        list.add(countrySupplier.get(Country::new, cursor.next()));
                  }
               } finally {
                     cursor.close();
               } 
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
              exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return list;

     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="public List<Country> findAllSorted(Sorted sorted)">

    @Override
    public List<Country>  findAllSorted(Sorted sorted) {
        List<Country> list = new ArrayList<>();
        try {
           MongoCollection<Document> collection = getCollection().get();
               MongoCursor<Document> cursor;
               		cursor = collection.find().allowDiskUse(Boolean.TRUE)
					.sort(sorted.getSort())
		.iterator();

               try{
                  while (cursor.hasNext()) {
                        list.add(countrySupplier.get(Country::new, cursor.next()));
                  }
               } finally {
                     cursor.close();
               } 
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
               exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return list;

     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="public Optional<Country> findByPk(String id )">

    public Optional<Country> findByPk(String id ) {
        try {
           MongoCollection<Document> collection = getCollection().get();
            Document doc = collection.find(eq("idcountry", id)).allowDiskUse(Boolean.TRUE).first();
            if(doc == null){
               return Optional.empty();
            }
            Country country = countrySupplier.get(Country::new, doc);
            return Optional.of(country);
       } catch (Exception e) {
            MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
             exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
       }
       return Optional.empty();
    }
// </editor-fold>


// <editor-fold defaultstate="collapsed" desc="public Optional<Country> findByPkInternal(String id, String mongodbDatabaseValue, String mongodbCollectionValue  )">

    public Optional<Country> findByPkInternal(String id , String mongodbDatabaseValue, String mongodbCollectionValue ) {
        try {
            MongoDatabase database = mongoClient.getDatabase(mongodbDatabaseValue);
            MongoCollection<Document> collection = database.getCollection(mongodbCollectionValue);
            Document doc = collection.find(eq("idcountry", id)).allowDiskUse(Boolean.TRUE).first();
            if(doc == null){
               return Optional.empty();
            }
            Country country = countrySupplier.get(Country::new, doc);
            return Optional.of(country);
       } catch (Exception e) {
            MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
             exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
       }
       return Optional.empty();
    }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="Long deleteByPK(String id )">

    @Override
    public Long deleteByPk(String id){
        try {
           MongoCollection<Document> collection = getCollection().get();
               MongoCursor<Document> cursor;
               Bson filter = Filters.eq("idcountry",id);

		com.mongodb.client.result.DeleteResult deleteResult = collection.deleteOne(filter);

               return deleteResult.getDeletedCount();
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
              exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return 0L;
     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="Long deleteMany(com.jmoordb.core.model.Search search)">

    @Override
    public Long deleteMany(com.jmoordb.core.model.Search search){
        try {
           MongoCollection<Document> collection = getCollection().get();
                Document whereCondition = new Document();
		whereCondition = search.getFilter();
		com.mongodb.client.result.DeleteResult deleteResult = collection.deleteMany(whereCondition);

               return deleteResult.getDeletedCount();
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
              exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return 0L;
     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="Long updateMany(Bson query, Bson update)">


   @Override
   public Long updateMany(Bson query, Bson update) {
          try {

              MongoCollection<Document> collection = getCollection().get();

              UpdateResult result = collection.updateMany(query, update);
              return result.getModifiedCount();
            } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
              exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
            }
             return 0L;
   }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="public String createIndex(Bson bson)">

@Override
public String createIndex(Bson bson) {
       String result = "";
       try {
           String mongodbDatabaseValue = mongodbDatabase;
           String mongodbCollectionValue = mongodbCollection;
           if (!getDynamicDatabase().equals("")) {
               mongodbDatabaseValue = getDynamicDatabase();
            }
            if (!getDynamicCollection().equals("")) {
                mongodbCollectionValue = getDynamicCollection();
            }
            MongoDatabase database = mongoClient.getDatabase(mongodbDatabaseValue);
            setDynamicDatabase("");
            MongoCollection<Document> collection = database.getCollection(mongodbCollectionValue);
            setDynamicCollection("");
            result = collection.createIndex(bson);
        } catch (Exception e) {
           MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
           exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
        }
        return result;
       }  // </editor-fold>;
// <editor-fold defaultstate="collapsed" desc="void dropIndex(Bson bson)">


@Override
public void dropIndex(Bson bson) {
try {
     String mongodbDatabaseValue = mongodbDatabase;
     String mongodbCollectionValue = mongodbCollection;
     if (!getDynamicDatabase().equals("")) {
         mongodbDatabaseValue = getDynamicDatabase();
     }
     if (!getDynamicCollection().equals("")) {
        mongodbCollectionValue = getDynamicCollection();
     }
     MongoDatabase database = mongoClient.getDatabase(mongodbDatabaseValue);
     setDynamicDatabase("");
     MongoCollection<Document> collection = database.getCollection(mongodbCollectionValue);
     setDynamicCollection("");
     collection.dropIndex(bson);
} catch (Exception e) {
     MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
     exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
}
}
 // </editor-fold>
// <editor-fold defaultstate="collapsed" desc="Optional<ListIndexesIterable<Document>> listIndexes()">

  @Override
  public Optional<ListIndexesIterable<Document>> listIndexes(){
         ListIndexesIterable<Document> result;
         try {
             String mongodbDatabaseValue = mongodbDatabase;
             String mongodbCollectionValue = mongodbCollection;
             if (!getDynamicDatabase().equals("")) {
                 mongodbDatabaseValue = getDynamicDatabase();
             }
             if (!getDynamicCollection().equals("")) {
               mongodbCollectionValue = getDynamicCollection();
             }
             MongoDatabase database = mongoClient.getDatabase(mongodbDatabaseValue);
             setDynamicDatabase("");
             MongoCollection<Document> collection = database.getCollection(mongodbCollectionValue);
             setDynamicCollection("");
             result = collection.listIndexes();
             return Optional.of(result);
           } catch (Exception e) {
             MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
             exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
           }
             return  Optional.empty();
   }
//  </editor-fold>
// <editor-fold defaultstate="collapsed" desc="Optional<MongoIterable<String>> listCollectionNames() ">


 @Override
 public Optional<MongoIterable<String>> listCollectionNames(){
        MongoIterable<String> result;
        try {
             String mongodbDatabaseValue = mongodbDatabase;
             String mongodbCollectionValue = mongodbCollection;
             if (!getDynamicDatabase().equals("")) {
                 mongodbDatabaseValue = getDynamicDatabase();
             }
             if (!getDynamicCollection().equals("")) {
                 mongodbCollectionValue = getDynamicCollection();
             }
             MongoDatabase database = mongoClient.getDatabase(mongodbDatabaseValue);
             setDynamicDatabase("");
             MongoCollection<Document> collection = database.getCollection(mongodbCollectionValue);
             setDynamicCollection("");
             result = database.listCollectionNames();
             return Optional.of(result);
         } catch (Exception e) {
             MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
             exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
          return  Optional.empty();
      }
 // </editor-fold>
// <editor-fold defaultstate="collapsed" desc="public Optional<MongoCollection<Document>> getCollection()">
 @Override
  public Optional<MongoCollection<Document>> getCollection() {

         try {
             String mongodbDatabaseValue = mongodbDatabase;
             String mongodbCollectionValue = mongodbCollection;
             if (!getDynamicDatabase().equals("")) {
                 mongodbDatabaseValue = getDynamicDatabase();
             }
             if (!getDynamicCollection().equals("")) {
                 mongodbCollectionValue = getDynamicCollection();
             }
             MongoDatabase database = mongoClient.getDatabase(mongodbDatabaseValue);
             setDynamicDatabase("");
             MongoCollection<Document> collection = database.getCollection(mongodbCollectionValue);
             setDynamicCollection("");
             return Optional.of(collection);
         } catch (Exception e) {
             MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
             exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return Optional.empty();
     }
// </editor-fold
// <editor-fold defaultstate="collapsed" desc="public void init()">


   @PostConstruct
    public void init() {
          try {

            } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
              exception = new JmoordbException(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
            }
   }
// </editor-fold>

}